@startuml 

' name:     Brandon Toups, Evan McCarthy
' email:    bmt0015        esm0012
' class:    COMP3710-001
' date:     3 May 2018
' file:     use-case-diagram.puml

title Use Case Diagram

actor User
actor Database

rectangle {

usecase "Login to the app" as uc1
usecase "Secondary login" as uc2
usecase "View settings" as uc3
usecase "Change settings" as uc4
usecase "Play the quiz" as uc5
usecase "Show result" as uc6
usecase "Fetch questions" as uc7
 User -- uc1
 Database -- uc7
uc1 ..> uc3: <<includes>>
uc3 <.. uc4: <<extends>>
uc1 <.. uc2: <<extends>>
uc1 ..> uc5: <<includes>>
uc5 ..> uc6: <<includes>>




}

@enduml
